version: "3.9"

services:
  askmypdf:
    build: .
    container_name: askmypdf-app
    ports:
      - "8002:8002"
    env_file:
      - .env
    volumes:
      - ./data:/data
    restart: unless-stopped
